language: node_js
node_js: 8.9.1
branches:
  only: master
cache: yarn
install: yarn
script:
- yarn build
deploy:
  api_key:
    secure: FX+eD+sJf2FsSKfyFZUyBnotcUsHllaupFfwGruw7aALf7Um3gXQJQ2jAeFZWgz6jDPLPNPkOXAxYgkDtebEtavbmCOsE1p6RGeStf9O4FdpWpHGiEolzIyVVR15m8lcyBMB4nsK6nmb650FlUISHEVuSWIhAQxw0+dpk4qDcRmzjdYPxNLaH2CVme5Ses2rb+C/jr5nuvyu3oJlZIF6z1X+ieDtV9BOswbKjqRrV9Bjt/P0kKoxyng8J/5l9g0um317pekzqhuWBhVM7dAEwL6Rm3H6QhNkYfiSFn747InqbnNTBi9o7SCYp9inxIh4i6XL5JIAqpnGity6ECGYlf2pzmuV5WhZlAnJimIFuAKXNY9vKnscz5kvwvFWVuzkASD8yZiehzJGZMnaCFxz3wgyUHInqqOUGLUfKTA2S1VEDt8oSVWTG+d8BlB2JRdo56yjqNAtfIc8uYcpEaaXE0sopiPnE/CEhVM8MjeAa0+lRFNyR82suXDxx0eeo68qKZQ7CKm8S45gzdo3i7jvpLP6VHTcUaKxIMmD38Yii83crs15dCLoDh8oOIPnOHh1DWaNuGEomKZm3KHw/UdpMReoRdkmluY2r6bYfBPAeEJ3KyKWBjfSOzAl9whq2Ajaksmw1RTsg/oDIJ+d3di7wlUMSUQlH8Np9/gNi5J7dt8=
  email: npmjs@charlesstover.com
  on:
    branch: master
  provider: npm
  skip_cleanup: true
